# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zky08KIAWqa2id0d-_4NsdaeKIbH8QaR
"""

# Online Python - IDE, Editor, Compiler, Interpreter
"""Ejercicio 3"""


remain = {
    "500":1,
    "200":1,
    "100":1,
    "50":1,
    "20":1,
    "10":1,
    "5":1,
    "1":1 
}
credit = 1000

opcion =''

while opcion!=4:
  print()
  print("\t.:MENU:.")
  print ("******************")
  print("1. Deposit the money into the account: ")
  print("2. Withdraw money from the account: ")
  print("3. Show available money: ")
  print("4. Exit")
  opcion = int(input("Select an option: "))
  print()


   
  if opcion==1:
    money=0
    extra = float(input("how much money you want to deposit -> "))
    credit+=extra
    for i in remain:
      number=0
      while extra >= int(i):
        remain[i]=remain[i]+1
        number+=1
        extra=extra-int(i)
        print(str(number) + (" bills" if int(i) >=10 else " bill") + " the " + i + " dollars")
        
            
  elif opcion==2:
    withdraw = float(input("how much money you want to withdraw -> "))
    
    if withdraw>credit:
        print("Doesn’t have that kind of money")
    
    else:
         credit -= withdraw
         for i in remain:
            number=0
            if withdraw >= int(i):
              while withdraw >= int(i):
                remain[i]=remain[i]-1
                number+=1
                withdraw=withdraw-int(i)
              print(str(number) + (" bills" if int(i) >=10 else " bill") + " the " + i + " dollars")


         print(f"money from the account: {credit} $")
             
  elif opcion==3:
     print(f"money from the account: {credit} $")
        
  elif opcion==4:
    print("Thanks for trusting Bank of America")
        
  else:
    print("Error,wrong choice of menu")

for i in remain:
  print(remain[i])